---
- name: Display network information
  hosts: all
  tasks:
    - name: Update facts
      ansible.builtin.setup:
        gather_subset: all_ipv4_addresses
      register: machine_facts
    - name: Display facts
      ansible.builtin.debug:
        var: machine_facts.ansible_facts.ansible_all_ipv4_addresses
