---

- hosts: all
  become: true
  tasks:

  - name: install cockpit pakage
    apt:
      name: cockpit
      #
# start and enable cockpit
#

- name: start cockpit
  service: name=cockpit state=started

- name: enable cockpit.socket
  service:  name=cockpit.socket enabled=yes

